server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/malware_analyze?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&serverTimezone=CTT
    username: root
    password: 5201314
    driver-class-name: com.mysql.jdbc.Driver
  data:
    mongodb:
      uri: mongodb://222.201.187.174:27017/cuckoo
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB
mybatis:
  type-aliases-package: com.code.scut.entity
  mapper-locations: classpath:mapper/*.xml

cuckoo:
  url: http://222.201.187.174
  port: 1337
  bearerToken: 2yIq75P0-Ch_HO1dZqgdDw


customValue:
  pathName: E:\\save


logging:
  file:
    name: mylogs.log
    path: E:/mylogs
